# Generated by Django 3.1.1 on 2020-10-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(db_column='user_id', max_length=11, primary_key=True, serialize=False)),
                ('state', models.CharField(db_column='use_state', max_length=255)),
            ],
        ),
    ]
