# Generated by Django 3.1.1 on 2020-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRPGHelper',
            fields=[
                ('id', models.AutoField(db_column='id', max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=255)),
                ('state', models.CharField(db_column='state', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='docs',
        ),
    ]
