# Generated by Django 3.1.1 on 2020-11-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201006_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trpghelper',
            name='username',
        ),
        migrations.AddField(
            model_name='trpghelper',
            name='roomName',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AddField(
            model_name='trpghelper',
            name='userName',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='trpghelper',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trpghelper',
            name='state',
            field=models.CharField(default='unknown', max_length=256),
        ),
    ]
