# Generated by Django 3.1.1 on 2020-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201123_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trpghelper',
            name='roomName',
            field=models.CharField(default='\x00', max_length=256),
        ),
        migrations.AlterField(
            model_name='trpghelper',
            name='state',
            field=models.CharField(default='\x00', max_length=256),
        ),
        migrations.AlterField(
            model_name='trpghelper',
            name='userName',
            field=models.CharField(default='\x00', max_length=256, unique=True),
        ),
    ]
